// state.js
export const state = {
  map: null,
  nazioniGlobal: [],
  mapDataGlobal: null,
  selectedCountryId: null,
  customNaps: [],
  nationBaseColorMap: new Map(),
  externalBlocsInfo: [],
  externalNapsList: [],
  externalNapsSet: new Set(),
  nationMap: new Map(),
  multiBlocMap: new Map(),
  blocColorMap: new Map(),
  baseGeoJSON: null,
  originalLabelsData: [],
  labelsData: [],
  mapSource: 'actual',
  coloringMode: 'diplomacy',
  patternImageCache: new Map(),
  flagImageCache: new Map(),
  labelCanvas: null,
  theme: 'dark',
  labelCtx: null,
  alliancesList: [],
  allianceColorMap: new Map(),
  nationAlliancesMap: new Map(),
  sphereMap: new Map(),
  spherePrimaries: new Set(),
  sphereInfo: [],
  diplomacyData: new Map(),
  centroids: new Map(),
  battleHeatmapData: null,
  regionData: null,
  regionCache: new Map(), // regionId → { position: [lng,lat], name: string }
  previousColoringMode: 'diplomacy',

};